### ISSUE TITLE
We will probably need a PEP

### ISSUE THREAD

**Issue by gvanrossum** [we-like-parsers/cpython#10]
Especially now that PyCon has been cancelled I expect that the best way to present our case to the core developers is through a PEP.

**Comment by pablogsal** [comment]
I started by forking the `peps` repo in our org: 

https://github.com/we-like-parsers/peps

I will start working on a first skeleton for the PEP so we can start iterating over. It should be easy to iterate as mainly all things will be "additive" until maybe the final revisions.

**Comment by pablogsal** [comment]
Apparently the language summit may happen in a remote form via zoom or similar but I think there is still value in doing the PEP given that not all core developers can attend even if the language summit is remoted (only the people that were registered to originally attend can join apparently).

Unless you think otherwise I would like to start working on the first skeleton of the PEP soonish.

What do you think?

**Comment by lysnikolaou** [comment]
I agree that at this point a PEP is the best way to present our proposal, even if the Language Summit is happening remotely after all. So it's a +1 from me. Please let me know, in case I can help out in any way.

Also, we should probably start preparing the slides of our Language Summit presentation, right?

**Comment by pablogsal** [comment]
> Also, we should probably start preparing the slides of our Language Summit presentation, right?

Yep, we can certainly reuse some of the PEP for that purpose even if that is not finished. That is why I would like to start the draft earlier.

**Comment by lysnikolaou** [comment]
Can we close this?
