### ISSUE TITLE
Some tests are currently failing

### ISSUE THREAD

**Issue by gvanrossum** [we-like-parsers/cpython#18]
@pablogsal Do you know what we can do about the test failures? It seems unrelated to our work, but since we have a custom test configuration I don't know what to do about it.

**Comment by lysnikolaou** [comment]
@gvanrossum I don't think they're unrelated to our work. I had a look at some of the failures and I think that it has to do with strings generated from `bytes` objects being passed to `PyPegen_ASTFromString` [here](https://github.com/we-like-parsers/cpython/blob/89c23850ceea714b26b68b7d468b0b48b922a601/Python/pythonrun.c#L1039).

If we just pass in a dummy string there, the failures should probably go away.

**Comment by pablogsal** [comment]
> I don't think they're unrelated to our work.

Yeah, currently these tests are failing

```
    test_builtin test_bytes test_compile test_decorators test_fstring
    test_keyword test_named_expressions test_parser
    test_source_encoding test_string_literals test_ucn test_unicode
    test_unicodedata
```

It looks likely related to the recent changes.

> strings generated from `bytes` objects being passed to `PyPegen_ASTFromString` [here](https://github.com/we-like-parsers/cpython/blob/89c23850ceea714b26b68b7d468b0b48b922a601/Python/pythonrun.c#L1039).

Do they go away if you remove that line (I cannot test myself right now)? They should because that is the only "change" that affects the interpreter, no?  That line was done to check that the symbols are exported correctly and that a C-API call from the interpreter works. We can remove it for now if you like until we have proper support.

**Comment by lysnikolaou** [comment]
> We can remove it for now if you like until we have proper support.

Yeah, open #19.

**Comment by lysnikolaou** [comment]
Would you mind disabling macOS and Windows tests though, since they're no help at all at the moment?

**Comment by pablogsal** [comment]
> Would you mind disabling macOS and Windows tests though, since they're no help at all at the moment?

👍
