### ISSUE TITLE
Add func_type_input to possible start rules

### ISSUE THREAD

**Issue by lysnikolaou** [we-like-parsers/cpython#36]

**Comment by lysnikolaou** [comment]
Does this need to be taken care of before merging into CPython?

**Comment by gvanrossum** [comment]
Aren’t there tests for it? It’s used by mypy, but I currently have trouble getting mypy to work with 3.9... I think we need to have it by beta 1, but not necessarily for alpha 6.

**Comment by lysnikolaou** [comment]
> Aren’t there tests for it?

I don't think so.

**Comment by gvanrossum** [comment]
Well, mypy seems to be borked in 3.9a5 anyway, so let's not worry about this yet.

**Comment by gvanrossum** [comment]
Also, mypy calls `ast.parse()` and it seems that doesn't yet use the new parser. Once it does this will become a necessity. But we'll have to support type comments in the grammar first then.

FWIW the mypy problems with 3.9a5 are due to Serhiy's simplifications to the AST for subscripts (https://github.com/python/cpython/pull/9605), and are up to the mypy team to fix (https://github.com/python/mypy/issues/8627).

IOW this is a loose end that we can handle after alpha 6.

**Comment by lysnikolaou** [comment]
This is now tracked in #95.
