### ISSUE TITLE
Add an API that invokes the new and the old parsers explicitly

### ISSUE THREAD

**Issue by lysnikolaou** [we-like-parsers/cpython#6]

**Comment by gvanrossum** [comment]
Is this about C-level APIs or Python-level APIs? We probably need both.

**Comment by pablogsal** [comment]
I will start working on the C-level API today. Some preliminary questions:

* For creating a C-API call that we can invoke instead of the old parser we need a compilation unit that is not prepared to be converted into a shared object (extension module). This suggests that maybe the best way is to separate the extension-creation related code from the API calls in `parse.c` so we can create the extension and include the compilation unit in `libpython.so` so we can call it from the core to create the AST instead of the old parser.

* Should we generate `parse.c` in `Parser` or maybe inside the `Python` directory for this purpose?

**Comment by lysnikolaou** [comment]
> For creating a C-API call that we can invoke instead of the old parser we need a compilation unit that is not prepared to be converted into a shared object (extension module). This suggests that maybe the best way is to separate the extension-creation related code from the API calls in parse.c so we can create the extension and include the compilation unit in libpython.so so we can call it from the core to create the AST instead of the old parser.
>
> Should we generate parse.c in Parser or maybe inside the Python directory for this purpose?

That's already fixed by #8. Pegen now generates parse.c into Modules/peg_parser/parse.c.

I've got another question. Maybe I don't understand the term API well enough, but it's not crystal clear to me what we wanna achieve with this. Do we want C-level and Python-level functions that just invoke the new parser (and if so, don't we already have `parse_string` and `parse_file`?) or do we want to have functions, which "disable" pgen and enable "pegen"? Or is it neither of those?

**Comment by pablogsal** [comment]
> That's already fixed by #8. Pegen now generates parse.c into Modules/peg_parser/parse.c.

Yup, but if we plan to (additionally?) link that against `libpython.so` (or the static binary if not `--enable-shared` we probably don't want it in `Modules` no?

**Comment by pablogsal** [comment]
> Do we want C-level and Python-level functions that just invoke the new parser (and if so, don't we already have `parse_string` and `parse_file`?) or do we want to have functions, which "disable" pgen and enable "pegen"?

We have those functions, but currently, they are in the extension module. If we want to be able to call `parse_string` and `parse_file` from anywhere in the C code, we need a slighly different structure, in which these functions are in a header file that is included in the `Include` directory and a compilation unit that is included with the core, so the linker can find the relevant code.

Notice that this is different from what we currently have that is an extension module, that is a shared object on its own that can be imported from Python (when you write `import pegen` what happens is that Python calls `dlopen` on the shared object and finds the relevant init symbol).

**Comment by lysnikolaou** [comment]
> > Do we want C-level and Python-level functions that just invoke the new parser (and if so, don't we already have `parse_string` and `parse_file`?) or do we want to have functions, which "disable" pgen and enable "pegen"?
> 
> We have those functions, but currently, they are in the extension module. If we want to be able to call `parse_string` and `parse_file` from anywhere in the C code (and we do in order to add a new code path for the new parser), we need a slightly different structure, in which these functions are in a header file that is included in the `Include` directory and a compilation unit that is included with the core, so the linker can find the relevant code.
> 
> Notice that this is different from what we currently have that is an extension module, that is a shared object on its own that can be imported from Python (when you write `import pegen` what happens is that Python calls `dlopen` on the shared object and finds the relevant init symbol).

Understood. Thanks for the explanation!

**Comment by lysnikolaou** [comment]
> * Should we generate `parse.c` in `Parser` or maybe inside the `Python` directory for this purpose?

My intuition tells me that `parse.c` belongs in `Parser`, but you know best.

**Comment by gvanrossum** [comment]
What we did so far was work through the changes in the grammar and the supporting C code needed to link with Python 3.9 and to be built and tested by the core's build machinery. Now that we've got that working it makes sense to move almost all of the code out of Modules/. This code should export C API functions to parse a string or a file, and a minimal module in Modules/ can be created that wraps just those. (We can use the `@trailer` syntax in python.gram to make the generated code export C APIs instead of a module.)

I'm torn whether it should go into Parser/ or Python/, because the old parser is really split between the two: the code that produces the *concrete* syntax tree is in Parser/, but the code that converts all that to an AST (both the internal and the external version) is in Python/.

[thinks about it]

Okay, let's put it in Parser/, since that's where I'd look for it. Regardless, anything that's exported by pegen.c or by parse_string.c needs to have its function name changed to `_Py<something>` (maybe `_PyPeg_<something>` for PEG-related things, and `_PyAST_<something>` for AST support?).

Eventually we should be looking to refactor ast.c so that we can share more code (IIRC the f-string processing code and a bunch of other things were almost literally copied from there). But that's a separate project to be undertaken later -- first we need proof-of-concept.

**Comment by lysnikolaou** [comment]
@pablogsal Are you working on this? Can I go ahead and give it a try?

**Comment by pablogsal** [comment]
> @pablogsal Are you working on this? Can I go ahead and give it a try?

I have started already but I didn't have time to go very far. If you would prefer to do this yourself I can start working on the first draft for the PEP (#10) instead.

**Comment by lysnikolaou** [comment]
> > @pablogsal Are you working on this? Can I go ahead and give it a try?
> 
> I have started already but I didn't have time to go very far. If you would prefer to do this yourself I can start working on the first draft for the PEP (#10) instead.

Could you push what you've done already? I'll have a look at it. I want to give it a try, but I'm not sure I'm gonna make it.

**Comment by pablogsal** [comment]
> Could you push what you've done already?

I am finishing some work-related stuff and as I finish I will try to push what I have :)

**Comment by pablogsal** [comment]
@lysnikolaou I have pushed my progress to the "c_api" branch:

https://github.com/we-like-parsers/cpython/tree/c_api

**Comment by lysnikolaou** [comment]
@pablogsal Perfect! Thanks a lot. 

I'll start working on it tomorrow morning.
