### ISSUE TITLE
Failure in test_compile: Unexpected LookupError

### ISSUE THREAD

**Issue by lysnikolaou** [we-like-parsers/cpython#63]
Current Parser:
```
╰─ ./python       
Python 3.9.0a5+ (heads/pegen:99a8e2fa08, Apr  9 2020, 16:19:04) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> code = '# -*- coding: badencoding -*-\n"\xc2\xa4"\n'
>>> eval(code)
'Â¤'
```

Pegen:
```
╰─ ./python -p new
Python 3.9.0a5+ (heads/pegen:99a8e2fa08, Apr  9 2020, 16:19:04) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> code = '# -*- coding: badencoding -*-\n"\xc2\xa4"\n'
>>> eval(code)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
LookupError: unknown encoding: badencoding
```

**Comment by gvanrossum** [comment]
Looks like exec and eval shouldn't look for a coding cookie at all (which makes sense since their argument is a string, which shouldn't be decoded).

**Comment by gvanrossum** [comment]
(However when the input is *bytes* we *should* look for a coding cookie.)

**Comment by lysnikolaou** [comment]
It's still not all that clear to me if this is a pegen problem or not. The seconf line of the input here contains bytes, doesn't it? So should we be looking for a coding cookie or not?

**Comment by gvanrossum** [comment]
Yes, it's a pegen problem. When the input has type `str`, the encoding is irrelevant -- a `str` instance is always Unicode. So Python ignores coding cookings in such cases, as the most likely reason there is a coding cookie is that the string was read from a file *and decoded*.

OTOH, when the input has type `bytes`, the coding cookie must be parsed and respected, because it tells us how the remaining bytes should be handled.

Compare:

```
>>> eval("# coding: bad\n42")
42
>>> eval(b"# coding: bad\n42")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 0
SyntaxError: unknown encoding: bad
>>> 
```
