### ISSUE TITLE
Rename functions to make smelly happy

### ISSUE THREAD

**Issue by lysnikolaou** [we-like-parsers/cpython#78]
How exactly should these be named? `_PyPegen_*`? And should we wrap each declaration with `PyAPI_FUNC`?

**Comment by gvanrossum** [comment]
`_PyPegen_` sounds like a fine prefix. Since these are not part of the API I don't think they need to be wrapped in `PyAPI_FUNC` -- IIUC that would make them available across shared libraries / DLLs, and we don't need that. (The APIs for which we need it are already marked up that way, in Includes/pegen_interface.h.)
