### ISSUE TITLE
Upstream review

### ISSUE THREAD

**Issue by lysnikolaou** [we-like-parsers/cpython#89]
Is it up to people to step up to review our PR or should we explicitly ask for it? Maybe on python-dev?

**Comment by pablogsal** [comment]
We can directly add people as reviewers in the PR (that's the most natural way normally). If that does not work we can send an email to python-dev. But we should wait first for the SC to approve the PEP because they may want changes (like no flag for instance) and we don't want people to review code that we may delete.

**Comment by pablogsal** [comment]
In other news, gentlemen, upstream CPython test suite is passing now:

https://github.com/python/cpython/pull/19503

🚀

**Comment by lysnikolaou** [comment]
Amazing news! 🎉 🎉 🚀 

Should I open a bpo issue? Will we need a bpo number?

**Comment by pablogsal** [comment]
> Will we need a bpo number?

Yes

> Should I open a bpo issue?

I would wait for the SC to pronounce first

**Comment by lysnikolaou** [comment]
> I would wait for the SC to pronounce first

Good point!

**Comment by gvanrossum** [comment]
Hm, I would not wait. The SC is likely to approve but we will only have 2 days until alpha 6. Realistically one day.

**Comment by gvanrossum** [comment]
I created an issue, https://bugs.python.org/issue40334. One last thing: we need a NEWS blurb.

**Comment by gvanrossum** [comment]
I'll write a news blurb.
